version: '2'
services:
    otsc-app:
        image: otsc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://otsc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=otsc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    otsc-mongodb:
        extends:
            file: mongodb.yml
            service: otsc-mongodb
